name: magnet
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pyarrow
  - cuda-toolkit=12.4  
  - cudnn
  - cuda-nvcc          
  - chainer
  - joblib
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pyside6
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - xgboost
  - pip:
    - "ray[tune]"
    - bayesian-optimization
    - biothings_client
    - causal-learn
    - cupy-cuda12x     
    - gcastle
    - gpucsl
    - graphviz
    - imbalanced-learn
    - ipykernel
    - keras
    - mygene
    - networkx
    - numba
    - optuna
    - pathos
    - pgmpy
    - pydot
    - pyvis
    - shap
    - tensorflow==2.20.0
    - torch==2.10.0
    - torch-geometric
    - torchvision
    - tqdm
    - nbconvert
    - openTSNE